= {lab_name} へようこそ！

== はじめに

OpenShift Virtualization を利用すると、仮想マシンを最新の Kubernetes ベースのインフラに移行できます。  
これにより、新しいアプリケーションの開発・提供だけでなく、既存アプリケーションのモダナイズも可能になります。  
また、仮想マシン・コンテナ・サーバーレス関数を組み合わせたアプリケーションを作成し、Kubernetes ネイティブのツールやパラダイムを使って一元管理できます。

このラボでは、Veeam Kasten K10 製品を使用して、仮想マシンのディザスタリカバリー、バックアップ、リストアを実践します。

== このラボで扱う内容

このラボでは、次の *5つ* の主要なセクションを学びます。

* _Veeam Kasten のインストール_  
  このセクションでは、任意の OpenShift クラスタに製品をインストールする方法を解説します。  
  なお、本ラボ環境ではすでに製品がインストールされているため、解説のみとなります。

* _ロケーションプロファイルの作成_  
  このセクションでは、仮想マシンのバックアップ先ストレージを指定するロケーションプロファイルを Kasten K10 に設定します。

* _仮想マシンの保護_  
  このセクションでは、仮想マシンに対して複数のバックアップおよびリストア操作を実行します。

* _オプション: マルチクラスタの設定_  
  このセクションでは、Kasten Multi-Cluster Manager の設定方法を学びます。  
  本ラボ環境は単一クラスタ構成のため、解説のみとなります。

* _オプション: ワークロードの移行_  
  このセクションでは、バックアップを別のクラスタにリストアする方法を解説します。  
  本ラボ環境は単一クラスタ構成のため、解説のみとなります。

== バージョン情報

このラボは以下のソフトウェアバージョンで構築されています。

* Red Hat OpenShift 4.16.x
* Red Hat OpenShift Virtualization 4.16.x
* Veeam Kasten K10 7.0.12

== ラボ環境の要件

* ブラウザーとインターネットにアクセス可能な PC を各参加者が用意してください。
* 一部のコピー＆ペースト機能が Firefox では動作しないため、Chromium ベースのブラウザーの利用を推奨します。
* リモートアクセスコンソールはデフォルトで米国キーボード配列を使用します。  
  他国のキーボードレイアウトを使用する場合は、特殊文字の位置を把握するか、サポートされているブラウザーでコピー＆ペースト機能を利用してください。

=== OpenShift コンソールの認証情報

* OpenShift クラスタコンソール: {openshift_console_url}[こちら^]  
* Kasten K10 ダッシュボード: {kasten_dashboard}[こちら^]  

両方の認証情報は以下の通りです。

* *ユーザー:* {user}  
* *パスワード:* {password}  

=== ユーザーに関する重要事項

====
[NOTE]

以降のラボガイドに掲載されているスクリーンショットでは、*user1* が参照されています。  
必ず *本文* の記載に従い、割り当てられた正しいユーザーを使用してください。
====
